import Link from 'next/link'

import { Container } from '@/components/Container'

const faqs = [
  [
    {
      question: 'Why do we need PepeChat?',
      answer:
        'We all have seen the problems with centralized media platforms where one entity controls the entire usage of the platform to their own will',
    },
    {
      question: 'How will the platform influence rising the price floor of the token',
      answer:
        'Revenue generated by our platform will be directly or indirectly invested back into our token and used in burns.',
    },
  ],
  [
    {
      question: 'How would we tackle some universally questionable content posted by users?',
      answer:
        'Our DAO, which is made up of our investors, can vote upon the removal of such content.',
    },
    {
      question: 'Why have a separate blockchain to run the app?',
      answer:
        'Our Blockchain is faster,cheaper and reliable with no downtime. Also to add, no external entity can shut down PepeChat since its a community owned Blockchain.',
    },
  ],
  [
    {
      question: 'Where is PepeChat based?',
      answer:
        'We prefer to keep our identity anonymous for now, but we are a multi-national team of professionals',
    },
    {
      question: 'Can you launch your own dapps and tokens on PepeChat Blockchain?',
      answer:
        'Thats the fun part, you absolutely can! We highly encourage and promote crypto activities on our blockchain to make our platform all in one for crypto users.',
    },
  ],
]

export function Faqs() {
  return (
    <section
      id="faqs"
      aria-labelledby="faqs-title"
      className="border-t border-gray-200 py-20 sm:py-32"
    >
      <Container>
        <div className="mx-auto max-w-2xl lg:mx-0">
          <h2
            id="faqs-title"
            className="text-3xl font-medium tracking-tight text-gray-900"
          >
            Frequently asked questions
          </h2>
          <p className="mt-2 text-lg text-gray-600">
            If you have anything to ask,{' '}
            <Link
              href="t.me/"
              className="text-gray-900 underline"
            >
              reach out to us
            </Link>
            .
          </p>
        </div>
        <ul
          role="list"
          className="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-8 sm:mt-20 lg:max-w-none lg:grid-cols-3"
        >
          {faqs.map((column, columnIndex) => (
            <li key={columnIndex}>
              <ul role="list" className="space-y-10">
                {column.map((faq, faqIndex) => (
                  <li key={faqIndex}>
                    <h3 className="text-lg font-semibold leading-6 text-gray-900">
                      {faq.question}
                    </h3>
                    <p className="mt-4 text-sm text-gray-700">{faq.answer}</p>
                  </li>
                ))}
              </ul>
            </li>
          ))}
        </ul>
      </Container>
    </section>
  )
}
